export const BRAND = {
  name: 'Ex-Serviceman Jobs',
  tagline: 'Connecting Talent With Opportunity',
  colors: {
    gold: '#F7A607',
    darkCharcoal: '#292e31',
    darkGrey: '#2e343d',
    deepDark: '#393939',
    nearBlack: '#242424',
    offWhite: '#f8f8f8',
  },
}

export const WORK_MODES = ['Remote', 'Hybrid', 'On-site'] as const
export const JOB_TYPES = ['Full-time', 'Part-time', 'Contract', 'Internship', 'Freelance'] as const
export const EXPERIENCE_LEVELS = ['Fresher', '0-1 years', '1-3 years', '3-5 years', '5-10 years', '10+ years'] as const
export const COMPANY_SIZES = ['1-10', '11-50', '51-200', '201-500', '501-1000', '1000+'] as const

export const INDUSTRIES = [
  'Information Technology',
  'Finance & Banking',
  'Healthcare',
  'E-commerce',
  'EdTech',
  'Manufacturing',
  'Marketing & Advertising',
  'Consulting',
  'Real Estate',
  'Logistics',
] as const

export const SKILL_SUGGESTIONS = [
  'React', 'Node.js', 'TypeScript', 'Python', 'Java', 'AWS', 'Docker',
  'Kubernetes', 'SQL', 'MongoDB', 'GraphQL', 'Next.js', 'Vue.js', 'Angular',
  'Flutter', 'React Native', 'Machine Learning', 'Data Science', 'DevOps',
  'UI/UX Design', 'Product Management', 'Business Analysis',
]

export const SAMPLE_JOBS = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'Razorpay',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=Razorpay&backgroundColor=1a56db',
    location: 'Bangalore, Karnataka',
    salaryMin: 1800000,
    salaryMax: 3000000,
    experience: '3-5 years',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'hybrid' as const,
    status: 'active' as const,
    applicants: 142,
    industry: 'Finance & Banking',
    department: 'Engineering',
    companyRating: 4.2,
    employerId: 'emp1',
    description: 'We are looking for a Senior Frontend Developer to join our team...',
    requirements: ['5+ years of experience', 'Strong React skills', 'TypeScript proficiency'],
    responsibilities: ['Build scalable UI components', 'Collaborate with designers', 'Code review'],
    benefits: ['Health insurance', 'Remote work', 'Stock options', 'Learning budget'],
  },
  {
    id: '2',
    title: 'React Native Developer',
    company: 'CRED',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=CRED&backgroundColor=7e3af2',
    location: 'Bangalore, Karnataka',
    salaryMin: 1500000,
    salaryMax: 2500000,
    experience: '2-4 years',
    skills: ['React Native', 'JavaScript', 'Redux', 'iOS', 'Android'],
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'remote' as const,
    status: 'active' as const,
    applicants: 89,
    industry: 'Finance & Banking',
    department: 'Mobile',
    companyRating: 4.5,
    employerId: 'emp2',
    description: 'Join CRED as a React Native Developer...',
    requirements: ['React Native expertise', 'Redux knowledge', 'Native modules experience'],
    responsibilities: ['Develop mobile features', 'Optimize performance', 'Testing'],
    benefits: ['ESOPs', 'Flexible hours', 'Health coverage'],
  },
  {
    id: '3',
    title: 'Full Stack Developer',
    company: 'Zepto',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=Zepto&backgroundColor=16a34a',
    location: 'Mumbai, Maharashtra',
    salaryMin: 1200000,
    salaryMax: 2200000,
    experience: '2-5 years',
    skills: ['Node.js', 'React', 'PostgreSQL', 'AWS', 'Docker'],
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'onsite' as const,
    status: 'active' as const,
    applicants: 213,
    industry: 'E-commerce',
    department: 'Engineering',
    companyRating: 3.9,
    employerId: 'emp3',
    description: 'Build the future of quick commerce with Zepto...',
    requirements: ['MERN stack', 'System design', 'Cloud experience'],
    responsibilities: ['Feature development', 'API design', 'Database optimization'],
    benefits: ['ESOP', 'Gym membership', 'Free meals'],
  },
  {
    id: '4',
    title: 'UI/UX Designer',
    company: 'Swiggy',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=Swiggy&backgroundColor=ea580c',
    location: 'Bangalore, Karnataka',
    salaryMin: 1000000,
    salaryMax: 1800000,
    experience: '2-4 years',
    skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'hybrid' as const,
    status: 'active' as const,
    applicants: 167,
    industry: 'E-commerce',
    department: 'Design',
    companyRating: 4.1,
    employerId: 'emp4',
    description: 'Design experiences that delight millions of users...',
    requirements: ['Figma expertise', 'Portfolio', 'Mobile-first design'],
    responsibilities: ['User research', 'Wireframing', 'Design systems'],
    benefits: ['Creative freedom', 'Team lunches', 'Conference budget'],
  },
  {
    id: '5',
    title: 'Backend Engineer',
    company: 'Meesho',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=Meesho&backgroundColor=7c3aed',
    location: 'Bangalore, Karnataka',
    salaryMin: 1400000,
    salaryMax: 2400000,
    experience: '3-6 years',
    skills: ['Go', 'Microservices', 'Kafka', 'Redis', 'Kubernetes'],
    postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'hybrid' as const,
    status: 'active' as const,
    applicants: 98,
    industry: 'E-commerce',
    department: 'Platform',
    companyRating: 4.3,
    employerId: 'emp5',
    description: 'Scale systems serving 100M+ users...',
    requirements: ['Go/Java', 'Distributed systems', 'Performance optimization'],
    responsibilities: ['Microservice design', 'Database scaling', 'On-call rotation'],
    benefits: ['High ownership', 'WFH options', 'ESOP'],
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'PhonePe',
    companyLogo: 'https://api.dicebear.com/7.x/initials/svg?seed=PhonePe&backgroundColor=5b21b6',
    location: 'Bangalore, Karnataka',
    salaryMin: 1600000,
    salaryMax: 2800000,
    experience: '4-7 years',
    skills: ['AWS', 'Terraform', 'Kubernetes', 'CI/CD', 'Monitoring'],
    postedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    type: 'full-time' as const,
    workMode: 'hybrid' as const,
    status: 'active' as const,
    applicants: 74,
    industry: 'Finance & Banking',
    department: 'Infrastructure',
    companyRating: 4.4,
    employerId: 'emp6',
    description: 'Build and maintain reliable infrastructure at scale...',
    requirements: ['AWS certified', 'Kubernetes expertise', 'Security knowledge'],
    responsibilities: ['Infrastructure as Code', 'CI/CD pipelines', 'Incident management'],
    benefits: ['Learning fund', 'Insurance', 'Stock options'],
  },
]

export const SAMPLE_COMPANIES = [
  { id: '1', name: 'Razorpay', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=Razorpay&backgroundColor=1a56db', industry: 'Fintech', size: '1000+', rating: 4.2, openPositions: 42, location: 'Bangalore' },
  { id: '2', name: 'CRED', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=CRED&backgroundColor=7e3af2', industry: 'Fintech', size: '501-1000', rating: 4.5, openPositions: 28, location: 'Bangalore' },
  { id: '3', name: 'Zepto', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=Zepto&backgroundColor=16a34a', industry: 'E-commerce', size: '1000+', rating: 3.9, openPositions: 67, location: 'Mumbai' },
  { id: '4', name: 'Swiggy', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=Swiggy&backgroundColor=ea580c', industry: 'Food Tech', size: '1000+', rating: 4.1, openPositions: 89, location: 'Bangalore' },
  { id: '5', name: 'Meesho', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=Meesho&backgroundColor=7c3aed', industry: 'E-commerce', size: '1000+', rating: 4.3, openPositions: 34, location: 'Bangalore' },
  { id: '6', name: 'PhonePe', logo: 'https://api.dicebear.com/7.x/initials/svg?seed=PhonePe&backgroundColor=5b21b6', industry: 'Fintech', size: '1000+', rating: 4.4, openPositions: 51, location: 'Bangalore' },
]
